### ISSUE TITLE
Mobile Version Post Design Bug

### ISSUE THREAD

**Issue by SethClydesdale** [SethClydesdale/forumactif-edge#10]
**Topic on forum :** http://fmdesign.forumotion.com/t1097-mobile-version-bug#24880

**Description :** There appears to be an issue with the responsiveness on some mobile devices. The problem is that there's a large space between the profile and message content. When viewing on mobile the profile should display horizontally above the post content, [like this](https://i97.servimg.com/u/f97/18/45/41/65/siri_f10.png), but that isn't the case here.

**Image :** http://img4.hostingpics.net/pics/696001fullsizeoutput35.jpg

**Todo :** 
1. The best place to start would be by looking over the CSS that concerns the responsiveness of posts, which is [here](https://github.com/SethClydesdale/forumactif-edge/blob/master/css/fa_edge.css#L2251).
2. [DDril](http://fmdesign.forumotion.com/t1097-mobile-version-bug#24947) mentioned that adjusting the width via the CP allows you to reproduce the issue. This is worth looking into as well.

**Comment by SethClydesdale** [comment]
I've located the issue and will send a fix online with patch 1.1.4. This problem comes from the CSS that's added via General Settings in the CP. The rules applied override the media query rules. All that's needed is to make the media query properties important.

Basically changing this : 
```css
  .post-inner { margin-left:0; }
  .postprofile {
    width:100%;
    margin:-10px 0 10px 0;
    float:none;
  }
```

Into this : 
```css
  .post-inner { margin:0 !important; }
  .postprofile {
    width:100%;
    margin:-10px 0 10px 0 !important;
    float:none !important;
  }
```

Since the fix has been found I'll be closing this issue and prepping v1.1.4 for production.
