### ISSUE TITLE
Who is online icon is not floated

### ISSUE THREAD

**Issue by SethClydesdale** [SethClydesdale/forumactif-edge#18]
**Topic on the forum :** http://fmdesign.forumotion.com/t1277-imagine-in-statistics#29567

**Description :** When adding a who is online icon via pics management, the icon is not floated to the left like it should be. It appears this portion was missed during initial development of Forumactif Edge. The CSS snippet below needs to be added to the stylesheets in the next patch.

```css
#i_whosonline {
  float:left;
  margin-right:6px;
}
 
#i_whosonline[src$="empty.gif"] { display:none; }
#wio_activity .txt-content > br:last-child { clear:both; }
```

**Extra note :** The icon may need to be floated to the right for RTL stylesheets. Keep that in mind.
