### ISSUE TITLE
Topic share actions lack margin and proper alignment

### ISSUE THREAD

**Issue by SethClydesdale** [SethClydesdale/forumactif-edge#19]
**Description :** The share actions above topics appear to be lacking both margin and proper alignment. This seems to be another thing I overlooked during initial development of Forumactif Edge.

![](https://i58.servimg.com/u/f58/18/45/41/65/captur13.png)

I prepped some CSS that'll fix both the margin and alignment in the next patch. Be sure to add it in.

```css
.topic-actions > p.right, .topic-actions > p.right > span {
  margin:0 3px;
}

.topic-actions > .pagination {
  margin:3px;
}
```
